
//----------------------------------------------------
// The following code was generated by CUP v0.11b 
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALS = 36; //done
  public static final int LSQUARE = 42; //done
  public static final int MINUS = 30; //done
  public static final int DISPLAY = 24; //done
  public static final int READOP = 8;  //done
  public static final int GREATER = 39; //done
  public static final int LPAREN = 19; //done
  public static final int INTEGER = 3; //done
  public static final int PLUSPLUS = 27; //done
  public static final int DIVIDE = 32; //done
  public static final int LESS = 38; //done
  public static final int STRUCT = 7; //done
  public static final int OR = 35; //done
  public static final int BOOLEAN = 2; //done
  public static final int COMMA = 22; //done
  public static final int RPAREN = 20; //done
  public static final int NOT = 33; //done
  public static final int COLON = 21; //done
  public static final int AND = 34; //done
  public static final int PLUS = 29; //done
  public static final int EOF = 0; //done
  public static final int MINUSMINUS = 28; //done
  public static final int RETURN = 13; //done
  public static final int TRUE = 5; //done
  public static final int RSQUARE = 1; //done
  public static final int LCURLY = 17; //done
  public static final int VOID = 4; //done
  public static final int NOTEQ = 37; //done
  public static final int WHILE = 12; //done
  public static final int LESSEQ = 40; //done
  public static final int ASSIGN = 26; //done
  public static final int IF = 10; //done
  public static final int DOT = 23; //done
  public static final int ID = 14; //done
  public static final int RCURLY = 18; //done
  public static final int INTLIT = 15; //done
  public static final int TIMES = 31; //done
  public static final int ELSE = 11; //done
  public static final int INPUT = 25; //done
  public static final int GREATEREQ = 41; //done
  public static final int STRINGLIT = 16; //done
  public static final int FALSE = 6; //done
  public static final int WRITEOP = 9; //done
}
